[package]
name = "sustain-metadata-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "sustain_metadata_remote"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
sustain-artwork = { path = "../artwork" }
ureq = { version = "3", features = ["json"] }

[lints]
workspace = true
