// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 AnnoyingTechnology

//! Adapt a local GiantSteps dataset checkout into a benchmark manifest.
//!
//! The GiantSteps Tempo and Key datasets (Knees et al., ISMIR'15) ship
//! per-track annotation files and md5 digests, but no audio: the audio is
//! Beatport previews fetched separately with the repos' own `audio_dl.sh`
//! (now pointing at the JKU mirror). This adapter reads a *pinned* local
//! checkout of one of those repos plus a local audio directory and emits a
//! [`crate::manifest`] TOML with ground-truth `bpm` / `key`. It never
//! downloads, and it never vendors audio or annotations into Sustain — the
//! source of truth stays the upstream checkout.
//!
//! See `docs/analysis-benchmark-corpora.md` for the pinned commits, the
//! licensing, and the full acquisition → adaptation → run sequence.

use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Serialize;

use crate::manifest::Task;

/// Which GiantSteps dataset is being adapted. The two share a layout
/// (`<stem>.<ext>` annotation files, `md5/<stem>.md5` digests, `<stem>.mp3`
/// audio) and differ only in the annotation directory, file extension,
/// ground-truth field, and the analyzer capability they exercise.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dataset {
    /// GiantSteps Tempo — per-track BPM in `annotations_v2/tempo/<stem>.bpm`.
    Tempo,
    /// GiantSteps Key — per-track key in `annotations/key/<stem>.key`.
    Key,
}

impl Dataset {
    /// Stable corpus id, used as the manifest `corpus_id`.
    fn corpus_id(self) -> &'static str {
        match self {
            Dataset::Tempo => "giantsteps_tempo",
            Dataset::Key => "giantsteps_key",
        }
    }

    /// Annotation directory, relative to the repo root.
    fn annotation_subdir(self) -> &'static str {
        match self {
            // v2 = the crowdsourced re-annotation (Schreiber & Müller, ISMIR'18).
            Dataset::Tempo => "annotations_v2/tempo",
            Dataset::Key => "annotations/key",
        }
    }

    /// Annotation file extension.
    fn annotation_ext(self) -> &'static str {
        match self {
            Dataset::Tempo => "bpm",
            Dataset::Key => "key",
        }
    }

    /// The single analyzer capability this corpus scores.
    fn task(self) -> Task {
        match self {
            Dataset::Tempo => Task::Bpm,
            Dataset::Key => Task::Key,
        }
    }

    /// Provenance note baked into the generated manifest.
    fn description(self) -> String {
        let (name, dir) = match self {
            Dataset::Tempo => (
                "GiantSteps Tempo (BPM ground truth)",
                "annotations_v2/tempo",
            ),
            Dataset::Key => ("GiantSteps Key (key ground truth)", "annotations/key"),
        };
        format!(
            "{name}, generated by `analysis-bench adapt-giantsteps` from {dir}. \
             Gitignored — do not edit; regenerate from the pinned upstream checkout. \
             Audio and annotations are external and uncommitted; see \
             docs/analysis-benchmark-corpora.md."
        )
    }
}

impl std::str::FromStr for Dataset {
    type Err = AdaptError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "tempo" => Ok(Dataset::Tempo),
            "key" => Ok(Dataset::Key),
            other => Err(AdaptError::UnknownDataset(other.to_string())),
        }
    }
}

/// Inputs to [`adapt`].
#[derive(Clone, Debug)]
pub struct AdaptOptions {
    /// Which dataset the checkout is.
    pub dataset: Dataset,
    /// Path to a local GiantSteps annotation-repo checkout.
    pub repo: PathBuf,
    /// Path to the directory holding the downloaded `<stem>.mp3` audio.
    pub audio_dir: PathBuf,
    /// Verify each audio file against the upstream `md5/<stem>.md5` digest.
    /// On by default, and strict: every emitted track must have an upstream
    /// digest, so a missing `md5/<stem>.md5` is a hard error rather than a
    /// silently unverified track. Pass `--no-md5` to opt out of verification
    /// entirely.
    pub verify_md5: bool,
}

/// Summary of an adaptation, for the CLI to report.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdaptReport {
    /// The corpus id written into the manifest.
    pub corpus_id: String,
    /// The serialized manifest TOML.
    pub manifest_toml: String,
    /// Tracks emitted into the manifest.
    pub track_count: usize,
    /// Annotation files skipped for lack of usable ground truth (tempo
    /// `0.0`/degenerate sentinels, empty key labels).
    pub skipped: usize,
    /// Emitted key labels the harness scorer cannot parse (so they will not
    /// be scored). Always 0 for the tempo dataset.
    pub key_unparseable: usize,
    /// Audio files whose md5 matched the upstream digest. `0` when
    /// verification is disabled (`--no-md5`); otherwise it equals
    /// `track_count`, since a missing digest is a hard error.
    pub md5_verified: usize,
}

/// Adaptation failures. Anything that would silently degrade a baseline —
/// missing audio, a checksum mismatch, an unparseable tempo annotation — is
/// a hard error rather than a quietly dropped track.
#[derive(Debug, thiserror::Error)]
pub enum AdaptError {
    /// `--dataset` was neither `tempo` nor `key`.
    #[error("unknown dataset {0:?}; expected `tempo` or `key`")]
    UnknownDataset(String),
    /// The annotation directory does not exist under the repo.
    #[error("annotation directory not found: {0} (is `--repo` a GiantSteps checkout?)")]
    AnnotationDirMissing(PathBuf),
    /// The annotation directory held no files with the expected extension.
    #[error("no `*.{ext}` annotation files under {dir}")]
    NoAnnotations {
        /// Expected annotation extension.
        ext: &'static str,
        /// Directory searched.
        dir: PathBuf,
    },
    /// A filesystem read failed.
    #[error("reading {path}: {source}")]
    Read {
        /// Path being read.
        path: PathBuf,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A path could not be represented as UTF-8 (TOML manifests are UTF-8).
    #[error("path is not valid UTF-8: {0}")]
    NonUtf8Path(PathBuf),
    /// An audio file path could not be canonicalized to an absolute path, so
    /// the manifest would otherwise be tied to the adapter's working
    /// directory.
    #[error("canonicalizing audio path {path}: {source}")]
    CanonicalizeAudio {
        /// Path that failed to canonicalize.
        path: PathBuf,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A tempo annotation did not parse as a number.
    #[error("{count} malformed tempo annotation(s); first: {first}")]
    MalformedAnnotation {
        /// How many failed to parse.
        count: usize,
        /// First offender.
        first: PathBuf,
    },
    /// Audio was missing for one or more annotated tracks.
    #[error("audio missing for {count} track(s); first: {first} (run the dataset's audio_dl.sh)")]
    MissingAudio {
        /// How many audio files were absent.
        count: usize,
        /// First absent path.
        first: PathBuf,
    },
    /// MD5 verification was enabled but one or more tracks had no upstream
    /// `md5/<stem>.md5` digest to verify against. A checksum-backed baseline
    /// requires every emitted track to be verifiable.
    #[error(
        "{count} track(s) have no upstream md5 digest to verify against; first: {first} \
         (the dataset ships md5/<stem>.md5; pass --no-md5 to skip verification)"
    )]
    MissingMd5 {
        /// How many tracks lacked an upstream md5 file.
        count: usize,
        /// The first absent `md5/<stem>.md5` path.
        first: PathBuf,
    },
    /// An upstream md5 file was not a single 32-hex digest.
    #[error("malformed upstream md5 file: {0}")]
    BadMd5File(PathBuf),
    /// A downloaded audio file's md5 did not match the upstream digest.
    #[error(
        "{count} audio file(s) failed md5 verification; first: {first} \
         (expected {expected}, got {actual})"
    )]
    Md5Mismatch {
        /// How many mismatched.
        count: usize,
        /// First mismatching audio path.
        first: PathBuf,
        /// Expected (upstream) digest.
        expected: String,
        /// Computed digest.
        actual: String,
    },
    /// The `md5sum` tool could not be run or behaved unexpectedly.
    #[error("{0}")]
    Md5Tool(String),
    /// The manifest failed to serialize to TOML.
    #[error("serializing manifest: {0}")]
    Serialize(#[source] toml::ser::Error),
    /// The generated manifest did not round-trip through the loader — an
    /// internal invariant violation, surfaced rather than swallowed.
    #[error("generated manifest failed to round-trip through the loader: {0}")]
    RoundTrip(String),
}

/// The serializable manifest document this adapter emits. A purpose-built
/// mirror of [`crate::manifest`] so we never have to make the *loader* types
/// `Serialize`; the round-trip self-check below guarantees the two agree.
#[derive(Serialize)]
struct ManifestDoc {
    meta: MetaDoc,
    options: OptionsDoc,
    #[serde(rename = "track")]
    tracks: Vec<TrackDoc>,
}

#[derive(Serialize)]
struct MetaDoc {
    corpus_id: String,
    description: String,
}

#[derive(Serialize)]
struct OptionsDoc {
    tasks: Vec<Task>,
}

#[derive(Serialize)]
struct TrackDoc {
    id: String,
    path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    bpm: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    key: Option<String>,
}

/// Ground truth resolved from one annotation file's contents.
enum GroundTruth {
    /// A usable tempo (BPM > 0).
    Bpm(f64),
    /// A key label, transcribed verbatim for the harness scorer to parse.
    Key(String),
    /// No usable ground truth (tempo `0.0` sentinel / degenerate, empty key).
    Skip,
    /// A tempo annotation that did not parse as a number.
    Malformed,
}

/// Interpret an annotation file's trimmed contents for `dataset`.
fn ground_truth(dataset: Dataset, value: &str) -> GroundTruth {
    match dataset {
        Dataset::Tempo => match value.parse::<f64>() {
            Ok(bpm) if bpm.is_finite() && bpm > 0.0 => GroundTruth::Bpm(bpm),
            // 0.0 is the documented "no tempo" sentinel; fold any other
            // non-positive/non-finite value in with it.
            Ok(_) => GroundTruth::Skip,
            Err(_) => GroundTruth::Malformed,
        },
        Dataset::Key => {
            if value.is_empty() {
                GroundTruth::Skip
            } else {
                GroundTruth::Key(value.to_string())
            }
        }
    }
}

/// Build a benchmark manifest from a local GiantSteps checkout + audio dir.
pub fn adapt(options: &AdaptOptions) -> Result<AdaptReport, AdaptError> {
    let dataset = options.dataset;
    let ann_dir = options.repo.join(dataset.annotation_subdir());
    if !ann_dir.is_dir() {
        return Err(AdaptError::AnnotationDirMissing(ann_dir));
    }
    let ext = dataset.annotation_ext();

    // Enumerate annotation files, sorted by stem so the manifest order is
    // deterministic regardless of directory iteration order.
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for entry in std::fs::read_dir(&ann_dir).map_err(|source| AdaptError::Read {
        path: ann_dir.clone(),
        source,
    })? {
        let path = entry
            .map_err(|source| AdaptError::Read {
                path: ann_dir.clone(),
                source,
            })?
            .path();
        if path.extension().and_then(|e| e.to_str()) != Some(ext) {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| AdaptError::NonUtf8Path(path.clone()))?
            .to_string();
        entries.push((stem, path));
    }
    if entries.is_empty() {
        return Err(AdaptError::NoAnnotations { ext, dir: ann_dir });
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut tracks: Vec<TrackDoc> = Vec::new();
    let mut skipped = 0_usize;
    let mut key_unparseable = 0_usize;
    let mut md5_verified = 0_usize;
    let mut malformed: Vec<PathBuf> = Vec::new();
    let mut missing_audio: Vec<PathBuf> = Vec::new();
    let mut missing_md5: Vec<PathBuf> = Vec::new();
    let mut md5_mismatch: Vec<(PathBuf, String, String)> = Vec::new();

    for (stem, ann_path) in &entries {
        let raw = std::fs::read_to_string(ann_path).map_err(|source| AdaptError::Read {
            path: ann_path.clone(),
            source,
        })?;
        let (bpm, key) = match ground_truth(dataset, raw.trim()) {
            GroundTruth::Bpm(bpm) => (Some(bpm), None),
            GroundTruth::Key(label) => {
                if crate::metrics::parse_key(&label).is_none() {
                    key_unparseable += 1;
                }
                (None, Some(label))
            }
            GroundTruth::Skip => {
                skipped += 1;
                continue;
            }
            GroundTruth::Malformed => {
                malformed.push(ann_path.clone());
                continue;
            }
        };

        let audio_path = options.audio_dir.join(format!("{stem}.mp3"));
        if !audio_path.is_file() {
            missing_audio.push(audio_path);
            continue;
        }

        if options.verify_md5 {
            let md5_path = options.repo.join("md5").join(format!("{stem}.md5"));
            match read_expected_md5(&md5_path)? {
                Some(expected) => {
                    let actual = file_md5(&audio_path)?;
                    if actual == expected {
                        md5_verified += 1;
                    } else {
                        md5_mismatch.push((audio_path, expected, actual));
                        continue;
                    }
                }
                None => {
                    missing_md5.push(md5_path);
                    continue;
                }
            }
        }

        // Canonicalize so the manifest carries an absolute path that does not
        // depend on the working directory of a later `analysis-bench run`.
        // The file exists (checked above), so failure is genuinely exceptional.
        let canonical =
            audio_path
                .canonicalize()
                .map_err(|source| AdaptError::CanonicalizeAudio {
                    path: audio_path.clone(),
                    source,
                })?;
        let path = canonical
            .to_str()
            .ok_or_else(|| AdaptError::NonUtf8Path(canonical.clone()))?
            .to_string();
        tracks.push(TrackDoc {
            id: stem.clone(),
            path,
            bpm,
            key,
        });
    }

    // Surface anything that would silently corrupt a baseline.
    if let Some(first) = malformed.first() {
        return Err(AdaptError::MalformedAnnotation {
            count: malformed.len(),
            first: first.clone(),
        });
    }
    if let Some(first) = missing_audio.first() {
        return Err(AdaptError::MissingAudio {
            count: missing_audio.len(),
            first: first.clone(),
        });
    }
    if let Some(first) = missing_md5.first() {
        return Err(AdaptError::MissingMd5 {
            count: missing_md5.len(),
            first: first.clone(),
        });
    }
    if let Some((first, expected, actual)) = md5_mismatch.first() {
        return Err(AdaptError::Md5Mismatch {
            count: md5_mismatch.len(),
            first: first.clone(),
            expected: expected.clone(),
            actual: actual.clone(),
        });
    }

    let track_count = tracks.len();
    let doc = ManifestDoc {
        meta: MetaDoc {
            corpus_id: dataset.corpus_id().to_string(),
            description: dataset.description(),
        },
        options: OptionsDoc {
            tasks: vec![dataset.task()],
        },
        tracks,
    };
    let manifest_toml = toml::to_string(&doc).map_err(AdaptError::Serialize)?;

    // Invariant: whatever we emit, the harness loader must accept. Parsing
    // it back as the real manifest type guards against this adapter's output
    // schema drifting from `crate::manifest`.
    toml::from_str::<crate::manifest::Manifest>(&manifest_toml)
        .map_err(|err| AdaptError::RoundTrip(err.to_string()))?;

    Ok(AdaptReport {
        corpus_id: dataset.corpus_id().to_string(),
        manifest_toml,
        track_count,
        skipped,
        key_unparseable,
        md5_verified,
    })
}

/// Read a single 32-hex md5 digest from an upstream `md5/<stem>.md5` file.
/// Returns `None` if the file is absent; the caller decides whether a missing
/// digest is fatal (it is, under default verification).
fn read_expected_md5(path: &Path) -> Result<Option<String>, AdaptError> {
    if !path.is_file() {
        return Ok(None);
    }
    let raw = std::fs::read_to_string(path).map_err(|source| AdaptError::Read {
        path: path.to_path_buf(),
        source,
    })?;
    let digest = raw
        .split_whitespace()
        .next()
        .unwrap_or_default()
        .to_ascii_lowercase();
    if !is_md5_hex(&digest) {
        return Err(AdaptError::BadMd5File(path.to_path_buf()));
    }
    Ok(Some(digest))
}

/// Compute a file's md5 via coreutils `md5sum`. The crate already shells out
/// to `git`; relying on coreutils keeps the dev tool dependency-free on the
/// Debian-first target rather than vendoring a hash implementation.
fn file_md5(path: &Path) -> Result<String, AdaptError> {
    let output = Command::new("md5sum")
        .arg("--")
        .arg(path)
        .output()
        .map_err(|source| {
            AdaptError::Md5Tool(format!(
                "could not run `md5sum` ({source}); install coreutils or pass --no-md5"
            ))
        })?;
    if !output.status.success() {
        return Err(AdaptError::Md5Tool(format!(
            "md5sum failed for {}: {}",
            path.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let digest = stdout
        .split_whitespace()
        .next()
        .unwrap_or_default()
        .to_ascii_lowercase();
    if !is_md5_hex(&digest) {
        return Err(AdaptError::Md5Tool(format!(
            "unexpected md5sum output for {}: {:?}",
            path.display(),
            stdout.trim()
        )));
    }
    Ok(digest)
}

/// A lowercase 32-character hex string.
fn is_md5_hex(s: &str) -> bool {
    s.len() == 32 && s.bytes().all(|b| b.is_ascii_hexdigit())
}

#[cfg(test)]
mod tests {
    use super::{AdaptError, AdaptOptions, Dataset, adapt, ground_truth};
    use std::fs;
    use std::path::Path;
    use tempfile::TempDir;

    /// md5("abc"), used by the verification tests.
    const MD5_ABC: &str = "900150983cd24fb0d6963f7d28e17f72";

    /// Write `contents` to `path`, creating parent directories.
    fn write(path: &Path, contents: &str) {
        fs::create_dir_all(path.parent().expect("fixture path has a parent"))
            .expect("create fixture dirs");
        fs::write(path, contents).expect("write fixture file");
    }

    /// A repo checkout + audio dir under one temp root.
    struct Fixture {
        root: TempDir,
    }

    impl Fixture {
        fn new() -> Self {
            Self {
                root: TempDir::new().expect("create temp dir"),
            }
        }
        fn repo(&self) -> std::path::PathBuf {
            self.root.path().join("repo")
        }
        fn audio(&self) -> std::path::PathBuf {
            self.root.path().join("audio")
        }
        fn annotation(&self, dataset: Dataset, stem: &str, contents: &str) {
            let dir = self.repo().join(dataset.annotation_subdir());
            write(
                &dir.join(format!("{stem}.{}", dataset.annotation_ext())),
                contents,
            );
        }
        fn audio_file(&self, stem: &str, contents: &str) {
            write(&self.audio().join(format!("{stem}.mp3")), contents);
        }
        fn md5_file(&self, stem: &str, digest: &str) {
            write(&self.repo().join("md5").join(format!("{stem}.md5")), digest);
        }
        fn options(&self, dataset: Dataset, verify_md5: bool) -> AdaptOptions {
            AdaptOptions {
                dataset,
                repo: self.repo(),
                audio_dir: self.audio(),
                verify_md5,
            }
        }
    }

    #[test]
    fn dataset_parses_from_argument() {
        assert_eq!(
            "tempo".parse::<Dataset>().expect("tempo parses"),
            Dataset::Tempo
        );
        assert_eq!("key".parse::<Dataset>().expect("key parses"), Dataset::Key);
        assert!(matches!(
            "beats".parse::<Dataset>(),
            Err(AdaptError::UnknownDataset(s)) if s == "beats"
        ));
    }

    #[test]
    fn ground_truth_classifies_each_annotation() {
        assert!(matches!(
            ground_truth(Dataset::Tempo, "127.0"),
            super::GroundTruth::Bpm(b) if (b - 127.0).abs() < f64::EPSILON
        ));
        assert!(matches!(
            ground_truth(Dataset::Tempo, "0.0"),
            super::GroundTruth::Skip
        ));
        assert!(matches!(
            ground_truth(Dataset::Tempo, "not-a-number"),
            super::GroundTruth::Malformed
        ));
        assert!(matches!(
            ground_truth(Dataset::Key, "C minor"),
            super::GroundTruth::Key(k) if k == "C minor"
        ));
        assert!(matches!(
            ground_truth(Dataset::Key, ""),
            super::GroundTruth::Skip
        ));
    }

    #[test]
    fn tempo_manifest_skips_zero_sentinels() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Tempo, "a.LOFI", "127.0");
        fx.annotation(Dataset::Tempo, "b.LOFI", "0.0"); // sentinel
        fx.annotation(Dataset::Tempo, "c.LOFI", "90.0");
        fx.audio_file("a.LOFI", "x");
        fx.audio_file("c.LOFI", "y");

        let report = adapt(&fx.options(Dataset::Tempo, false)).expect("adapt tempo");
        assert_eq!(report.track_count, 2);
        assert_eq!(report.skipped, 1);
        assert_eq!(report.corpus_id, "giantsteps_tempo");
        assert!(report.manifest_toml.contains("tasks = [\"bpm\"]"));
        assert!(report.manifest_toml.contains("id = \"a.LOFI\""));
        assert!(report.manifest_toml.contains("bpm = 127.0"));
        assert!(report.manifest_toml.contains("id = \"c.LOFI\""));
        // The sentinel track must not appear.
        assert!(!report.manifest_toml.contains("b.LOFI"));
    }

    #[test]
    fn key_manifest_transcribes_labels_and_counts_unparseable() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Key, "x.LOFI", "C minor");
        fx.annotation(Dataset::Key, "y.LOFI", "G major");
        fx.annotation(Dataset::Key, "z.LOFI", "bogus"); // parses to nothing
        for stem in ["x.LOFI", "y.LOFI", "z.LOFI"] {
            fx.audio_file(stem, "x");
        }

        let report = adapt(&fx.options(Dataset::Key, false)).expect("adapt key");
        assert_eq!(report.track_count, 3);
        assert_eq!(report.skipped, 0);
        assert_eq!(report.key_unparseable, 1);
        assert!(report.manifest_toml.contains("tasks = [\"key\"]"));
        assert!(report.manifest_toml.contains("key = \"C minor\""));
        assert!(report.manifest_toml.contains("key = \"bogus\""));
    }

    #[test]
    fn missing_audio_is_a_hard_error() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Tempo, "a.LOFI", "120.0");
        // No audio written.
        let err = adapt(&fx.options(Dataset::Tempo, false)).expect_err("missing audio errors");
        assert!(matches!(err, AdaptError::MissingAudio { count: 1, .. }));
    }

    #[test]
    fn missing_annotation_dir_is_an_error() {
        let fx = Fixture::new();
        fs::create_dir_all(fx.repo()).expect("create repo dir");
        let err = adapt(&fx.options(Dataset::Key, false)).expect_err("missing dir errors");
        assert!(matches!(err, AdaptError::AnnotationDirMissing(_)));
    }

    #[test]
    fn empty_annotation_dir_is_an_error() {
        let fx = Fixture::new();
        fs::create_dir_all(fx.repo().join(Dataset::Tempo.annotation_subdir()))
            .expect("create annotation dir");
        let err = adapt(&fx.options(Dataset::Tempo, false)).expect_err("empty dir errors");
        assert!(matches!(err, AdaptError::NoAnnotations { .. }));
    }

    #[test]
    fn md5_verification_passes_for_matching_audio() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Tempo, "a.LOFI", "128.0");
        fx.audio_file("a.LOFI", "abc");
        fx.md5_file("a.LOFI", MD5_ABC);

        let report = adapt(&fx.options(Dataset::Tempo, true)).expect("adapt with md5");
        assert_eq!(report.track_count, 1);
        assert_eq!(report.md5_verified, 1);
    }

    #[test]
    fn md5_mismatch_is_a_hard_error() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Tempo, "a.LOFI", "128.0");
        fx.audio_file("a.LOFI", "abc");
        fx.md5_file("a.LOFI", "00000000000000000000000000000000");

        let err = adapt(&fx.options(Dataset::Tempo, true)).expect_err("md5 mismatch errors");
        assert!(matches!(err, AdaptError::Md5Mismatch { count: 1, .. }));
    }

    #[test]
    fn missing_md5_file_is_a_hard_error_with_verification_on() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Tempo, "a.LOFI", "128.0");
        fx.audio_file("a.LOFI", "abc");
        // No md5 file written.

        // Default verification is strict: an emitted track with no upstream
        // digest fails rather than slipping into the baseline unverified.
        let err = adapt(&fx.options(Dataset::Tempo, true))
            .expect_err("missing md5 errors when verifying");
        assert!(matches!(err, AdaptError::MissingMd5 { count: 1, .. }));

        // `--no-md5` is the explicit escape hatch: the same checkout adapts.
        let report = adapt(&fx.options(Dataset::Tempo, false)).expect("adapt with --no-md5");
        assert_eq!(report.track_count, 1);
        assert_eq!(report.md5_verified, 0);
    }

    #[test]
    fn relative_audio_dir_emits_a_canonical_absolute_path() {
        let fx = Fixture::new();
        fx.annotation(Dataset::Tempo, "a.LOFI", "128.0");
        fx.audio_file("a.LOFI", "abc");

        // Drive the adapter with an audio directory expressed *relative* to
        // the process working directory (built by walking up to the
        // filesystem root, then back down to the temp fixture — no cwd
        // mutation, so it is safe under parallel test execution).
        let cwd = std::env::current_dir().expect("cwd");
        let depth = cwd
            .components()
            .filter(|c| matches!(c, std::path::Component::Normal(_)))
            .count();
        let mut relative_audio = std::path::PathBuf::new();
        for _ in 0..depth {
            relative_audio.push("..");
        }
        let absolute_audio = fx.audio();
        relative_audio.push(
            absolute_audio
                .strip_prefix("/")
                .expect("absolute temp path"),
        );
        assert!(
            relative_audio.is_relative(),
            "test drives a relative --audio"
        );

        let options = AdaptOptions {
            dataset: Dataset::Tempo,
            repo: fx.repo(),
            audio_dir: relative_audio,
            verify_md5: false,
        };
        let report = adapt(&options).expect("adapt with relative audio dir");

        // The emitted path is the canonical absolute audio path, independent
        // of any future caller's working directory.
        let expected = absolute_audio
            .join("a.LOFI.mp3")
            .canonicalize()
            .expect("canonicalize expected audio path");
        let expected_str = expected.to_str().expect("utf-8 path");
        assert!(
            std::path::Path::new(expected_str).is_absolute(),
            "expected path is absolute"
        );
        assert!(
            report
                .manifest_toml
                .contains(&format!("path = \"{expected_str}\"")),
            "manifest should carry the canonical absolute path {expected_str:?}; got:\n{}",
            report.manifest_toml
        );
    }
}
