[package]
name = "sustain-ui-gtk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "sustain_ui_gtk"
path = "src/lib.rs"

[dependencies]
async-channel = "2"
gtk.workspace = true
hashlink = "0.12.0"
rusqlite = { version = "0.39.0", features = ["bundled"] }
sustain-app-runtime = { path = "../app_runtime" }
sustain-artwork = { path = "../artwork" }
sustain-desktop = { path = "../desktop" }
sustain-profiler = { path = "../profiler" }

[lints]
workspace = true
